version:  '2'
services:

  master:
    image: solomonfield/alluxio:1.7.0
    container_name: hadoop-master
    networks:
      default:
        ipv4_address: 172.18.0.110
    extra_hosts:
      - "hadoop-slave1:172.18.0.111"
      - "hadoop-slave2:172.18.0.112"
      - "hadoop-slave3:172.18.0.113"
      - "hadoop-slave4:172.18.0.114"
    hostname: hadoop-master
    ports: 
      - "19010:22"
      - "50070:50070"
      - "8088:8088"
      - "16010:16010"
      - "19999:19999"
    volumes:
      - ~/Public/repo/BasicTask/PASA_CLASS/dockerfiles/share/:/root/experiment/
    environment:
      ROLE: master
    tty: true
    stdin_open: true

  slave1:
    image: solomonfield/alluxio:1.7.0
    container_name: hadoop-slave1
    networks:
      default:
        ipv4_address: 172.18.0.111
    extra_hosts:
      - "hadoop-master:172.18.0.110"
      - "hadoop-slave2:172.18.0.112"
      - "hadoop-slave3:172.18.0.113"
      - "hadoop-slave4:172.18.0.114"
    hostname: hadoop-slave1
    ports: 
      - "19011:22"
    environment:
      ROLE: slave
    tty: true
    stdin_open: true

  slave2:
    image: solomonfield/alluxio:1.7.0
    container_name: hadoop-slave2
    networks:
      default:
        ipv4_address: 172.18.0.112
    extra_hosts:
      - "hadoop-master:172.18.0.110"
      - "hadoop-slave1:172.18.0.111"
      - "hadoop-slave3:172.18.0.113"
      - "hadoop-slave4:172.18.0.114"
    hostname: hadoop-slave2
    ports: 
      - "19012:22"
    environment:
      ROLE: slave
    tty: true
    stdin_open: true

  slave3:
    image: solomonfield/alluxio:1.7.0
    container_name: hadoop-slave3
    networks:
      default:
        ipv4_address: 172.18.0.113
    extra_hosts:
      - "hadoop-master:172.18.0.110"
      - "hadoop-slave1:172.18.0.111"
      - "hadoop-slave2:172.18.0.112"
      - "hadoop-slave4:172.18.0.114"
    hostname: hadoop-slave3
    ports: 
      - "19013:22"
    environment:
      ROLE: slave
    tty: true
    stdin_open: true

  slave4:
    image: solomonfield/alluxio:1.7.0
    container_name: hadoop-slave4
    networks:
      default:
        ipv4_address: 172.18.0.114
    extra_hosts:
      - "hadoop-master:172.18.0.110"
      - "hadoop-slave1:172.18.0.111"
      - "hadoop-slave2:172.18.0.112"
      - "hadoop-slave3:172.18.0.113"
    hostname: hadoop-slave4
    ports: 
      - "19014:22"
    environment:
      ROLE: slave
    tty: true
    stdin_open: true

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
        gateway: 172.18.0.249

